/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.util.Random;

/**
 *
 * @author edvin.bergstrom
 */
public class PVE extends javax.swing.JFrame {

    /**
     * Creates new form PVE
     */
    public PVE() {
        initComponents();
    }

    static boolean easy;
    static PVE pve;
    int totalP;
    boolean forst = true;
    Random ra = new Random();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_1 = new javax.swing.JButton();
        p_2 = new javax.swing.JButton();
        comp = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        compAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_1.setText("+1");
        p_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_1ActionPerformed(evt);
            }
        });

        p_2.setText("+2");
        p_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_2ActionPerformed(evt);
            }
        });

        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_1)
                .addGap(18, 18, 18)
                .addComponent(p_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p_1)
                        .addComponent(p_2))
                    .addComponent(compAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_1ActionPerformed
        // TODO add your handling code here:
        totalP++;
        if (forst){
            if (ra.nextBoolean()){
                comp();
                System.out.println("datorn börjar");
            }
            System.out.println("jag börjar");
            forst=false;
        }
        total.setText(String.valueOf(totalP));
        if (totalP >= 21){
            total.setText("player 1 vann   " + totalP);
            forst=true;
            p_1.setEnabled(false);
            p_2.setEnabled(false);
            return;
        }
        comp();
        if (totalP >= 21){
            forst=true;
            total.setText("datorn vann   " + totalP);
            p_1.setEnabled(false);
            p_2.setEnabled(false);
        }

    }//GEN-LAST:event_p_1ActionPerformed

    private void comp() {
        int compadd = 0;
        if (!easy) {
            if ((totalP + 1) % 3 == 0) {
                compadd = 1;
            } else if ((totalP + 2) % 3 == 0) {
                compadd = 2;
            } else {
                compadd= 1;
            }
            totalP += compadd;
        }
        else {
            compadd= ra.nextInt(2)+1;
            totalP += compadd;

        }
        compAdd.setText(String.valueOf(compadd));
        total.setText(String.valueOf(totalP));

    }

    private void p_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_2ActionPerformed
        // TODO add your handling code here:

        if (forst){
            if (ra.nextBoolean()){
                comp();

                System.out.println("datorn börjar");
            }
            System.out.println("jag börjar");
            forst=false;
        }

        totalP++;
        totalP++;

        total.setText(String.valueOf(totalP));
        if (totalP >= 21){
            total.setText("player 1 vann   " + totalP);
            forst=true;
            p_1.setEnabled(false);
            p_2.setEnabled(false);
            return;
        }
        comp();
        if (totalP >= 21){
            total.setText("datorn vann   " + totalP);
            forst=true;
            p_1.setEnabled(false);
            p_2.setEnabled(false);
        }

    }//GEN-LAST:event_p_2ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        Index framePVE = new Index();
        framePVE.setVisible(true);
        pve.setVisible(false);

    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pve = new PVE();
                pve.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comp;
    private javax.swing.JLabel compAdd;
    private javax.swing.JButton exit;
    private javax.swing.JButton p_1;
    private javax.swing.JButton p_2;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
