/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import javax.swing.*;
import java.net.MalformedURLException;
import java.net.URL;

/**
 *
 * @author edvin.bergstrom
 */
public class PVP extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PVP() {
        ImageIcon splach = null;
        try{
            splach= new ImageIcon(new URL("https","s-media-cache-ak0.pinimg.com","/736x/c6/20/ca/c620caef7766c43a20b3ab81b2ebcbc0.jpg"));
        }catch (MalformedURLException e) {
            e.printStackTrace();
        }
        this.setContentPane(new JLabel(splach));
        setResizable(false);

        initComponents();
        this.setLocationRelativeTo(null);
        //start.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1_1 = new javax.swing.JButton();
        p1_2 = new javax.swing.JButton();
        p2_2 = new javax.swing.JButton();
        p2_1 = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        start = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p1_1.setText("+1");
        p1_1.setEnabled(false);
        p1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1_1ActionPerformed(evt);
            }
        });

        p1_2.setText("+2");
        p1_2.setEnabled(false);
        p1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1_2ActionPerformed(evt);
            }
        });

        p2_2.setText("+2");
        p2_2.setEnabled(false);
        p2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2_2ActionPerformed(evt);
            }
        });

        p2_1.setText("+1");
        p2_1.setEnabled(false);
        p2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2_1ActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        exit.setText("Back");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(p2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(exit)
                .addGap(39, 39, 39)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int toptaP;

    private void p1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1_1ActionPerformed
        // TODO add your handling code here:
        toptaP++;
        total.setText("Total :  "+toptaP);
        if (toptaP>= 21){
            total.setText("Vänster vann med " + toptaP + " poäng");
            start.setVisible(true);
            p1_1.setEnabled(false);
            p1_2.setEnabled(false);
            p2_2.setEnabled(false);
            p2_1.setEnabled(false);
            return;
        }
        p1_1.setEnabled(false);
        p1_2.setEnabled(false);
        p2_2.setEnabled(true);
        p2_1.setEnabled(true);

    }//GEN-LAST:event_p1_1ActionPerformed

    private void p1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1_2ActionPerformed
        // TODO add your handling code here:
        toptaP+=2;
        total.setText("Total :  "+toptaP+"");
        if (toptaP>= 21){
            total.setText("Vänster vann med " + toptaP + " poäng");
            start.setVisible(true);
            p1_1.setEnabled(false);
            p1_2.setEnabled(false);
            p2_2.setEnabled(false);
            p2_1.setEnabled(false);
            return;
        }
        p1_1.setEnabled(false);
        p1_2.setEnabled(false);
        p2_2.setEnabled(true);
        p2_1.setEnabled(true);
    }//GEN-LAST:event_p1_2ActionPerformed

    private void p2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2_1ActionPerformed
        // TODO add your handling code here:
        toptaP++;
        total.setText("Total :  "+toptaP+"");
        if (toptaP>= 21){
            total.setText("Höger vann med " + toptaP + " poäng");
            start.setVisible(true);
            p1_1.setEnabled(false);
            p1_2.setEnabled(false);
            p2_2.setEnabled(false);
            p2_1.setEnabled(false);
            return;
        }
        p1_1.setEnabled(true);
        p1_2.setEnabled(true);
        p2_2.setEnabled(false);
        p2_1.setEnabled(false);
    }//GEN-LAST:event_p2_1ActionPerformed

    private void p2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2_2ActionPerformed
        // TODO add your handling code here:
        toptaP+=2;
        total.setText("Total :  "+toptaP+"");
        if (toptaP>= 21){
            total.setText("Höger vann med " + toptaP + " poäng");

            p1_1.setEnabled(false);
            p1_2.setEnabled(false);
            p2_2.setEnabled(false);
            p2_1.setEnabled(false);
            start.setVisible(true);
            return;
        }
        p1_1.setEnabled(true);
        p1_2.setEnabled(true);
        p2_2.setEnabled(false);
        p2_1.setEnabled(false);
    }//GEN-LAST:event_p2_2ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        Index.index.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        p1_1.setEnabled(true);
        p1_2.setEnabled(true);
        p2_2.setEnabled(true);
        p2_1.setEnabled(true);
        toptaP = 0;
        total.setText("Total  :   " + toptaP);
        start.setVisible(false);
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new PVP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton p1_1;
    private javax.swing.JButton p1_2;
    private javax.swing.JButton p2_1;
    private javax.swing.JButton p2_2;
    private javax.swing.JToggleButton start;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
